# Copyright (C) {2024} {GLM, PB, AE, JMM}
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Script to run simulations to asses the power of the GoF tests.
#
# This script runs the pre-inference and post-inference GoF tests on 3 datasets:
# - The toy "gaussianlaplace" example;
# - The simple Population Genetics "depindep" example;
# - The more complex "human" example.
# Computations can be intensive, especially for the post-inference GoF test in the Human-like example.
#
# INPUTS:
#   - Result tables generated by script `01_gof_simulaiton_study.R`
#
# OUTPUTS:
#   - PDF plots of the results

library(here)
library(ggplot2)
library(tidyr)

################################################################################
# Load Data
datestamp_day <- "2024-04-24"
all_res_files <- list.files(path = here("results"), pattern = paste0(datestamp_day, "_*.*.rds"), full.names = TRUE)
all_res <- lapply(all_res_files, function(ff) readRDS(file = ff))

results_name <- paste0(datestamp_day, "_gof_resim_all")

columnwidth <- 3 # in inches # 1 point / 72 = 1 inch
twocolumnwidth <- 6

################################################################################
# Plot power - format
format_plot <- function(res, score, name) {
  # power
  datpower <- do.call(cbind, lapply(res[c(1,2)], function(rr) rr[[score]]))
  datpower <- as.data.frame(datpower)
  datpower$K <- rownames(datpower)
  datpower <- tidyr::pivot_longer(datpower, cols = -K, names_to = "score", values_to = name)
  # sd
  datpowersd <- do.call(cbind, lapply(res[c(1,2)], function(rr) rr[[paste0("sd_", score)]]))
  datpowersd <- as.data.frame(datpowersd)
  datpowersd$K <- rownames(datpowersd)
  datpowersd <- tidyr::pivot_longer(datpowersd, cols = -K, names_to = "score", values_to = paste0("sd_", name))
  # merge
  datpower <- merge(datpower, datpowersd)
  # parameters
  datpower$dataset <- res$dataset
  datpower$test_in_alternative <- res$test_in_alternative
  datpower$method <- res$method
  datpower$nref <- res$nref
  datpower$npost <- res$npost
  return(datpower)
}

datpower <- lapply(all_res, format_plot, score = "pow_5%", name = "power")
datpower <- do.call(rbind, datpower)
datpower <- subset(datpower, test_in_alternative == TRUE)
datpower$eps <- datpower$npost / datpower$nref
datpower$dataset <- factor(datpower$dataset, levels = c("gaussianlaplace", "depindep", "human"))
# datpower$nref <- factor(datpower$nref)
levels(datpower$dataset) <- c("Laplace - Gaussian", "Dep-Indep", "Human-like")

datpowermax <- subset(datpower, (K == "max" & score == "lof") |  (K == 1 & score == "kNN"))
datpower <- subset(datpower, K != "max")
datpower$K <- as.numeric(datpower$K)

datpowermax$score <- factor(datpowermax$score, levels = c("lof", "kNN"))
levels(datpowermax$score) <- c("LOF", "kNN")

################################################################################
# Plot power - prior

datpowerprior <- subset(datpower, method == "prior")
datpowermaxprior <- subset(datpowermax, method == "prior")


p <- ggplot(datpowermaxprior, aes(x = nref, y = power, color = score)) +
  geom_point() + geom_line(aes(group = interaction(score))) +
  # geom_linerange(aes(ymin = power + sd_power, ymax = power - sd_power)) +
  # facet_grid(row = vars(dataset), scales = "free") +
  facet_wrap(vars(dataset), scales = "free_y") +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 2), title = element_blank())) +
  theme_bw() +
  xlab(expression(N[ref]+N[calib])) +
  # scale_x_continuous(breaks = c(500, 1:5*1000)) +
  ylab("Estimated Power") +
  # ggtitle("Prior GOF") +
  theme(text = element_text(size = 9),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.99, 0.5),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(9, 'pt'),
        # plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
# colorblindr::cvd_grid(p)
p
colorblindr::cvd_grid()

ggsave(filename = here("result_figures", paste0(results_name, "_power_prior_max.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = 0.7 * columnwidth,
       unit = "in")


################################################################################
# Plot power - prior - K varying

datpowerprior$score <- factor(datpowerprior$score, levels = c("lof", "kNN"))
levels(datpowerprior$score) <- c("LOF", "kNN")
datpowerprior$nref <- factor(datpowerprior$nref, levels = c(500, 1000, 2000, 3000, 4000, 5000))
levels(datpowerprior$nref) <- paste0("N[ref]+N[calib]==",levels(datpowerprior$nref))
datpowermaxprior$nref <- factor(datpowermaxprior$nref, levels = c(500, 1000, 2000, 3000, 4000, 5000))
levels(datpowermaxprior$nref) <- paste0("N[ref]+N[calib]==",levels(datpowermaxprior$nref))

p <- ggplot(datpowerprior, aes(x = K, y = power, color = score)) +
  geom_point() + geom_line(aes(group = interaction(method, score, nref))) +
  geom_abline(data = datpowermaxprior, aes(intercept = power, slope = 0, color = score), show.legend = FALSE) +
  facet_grid(row = vars(nref), col = vars(dataset), labeller = label_parsed) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 1), title = element_blank())) +
  theme_bw() +
  xlab(expression(k)) +
  theme(text = element_text(size = 9),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.3, 0.01),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(9, 'pt'),
        # plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
p

ggsave(filename = here("result_figures", paste0(results_name, "_power_prior_all_K.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = twocolumnwidth,
       unit = "in")

################################################################################
# Plot power - prior vs localized prior

datpowermaxpriorpost <- subset(datpowermax, method == "prior" | (method == "post" & nref == 50000 & npost == 500) | (method == "post" & nref == 100000 & npost == 1000))
datpowermaxpriorpost$method <- factor(datpowermaxpriorpost$method, levels = c("prior", "post"))
levels(datpowermaxpriorpost$method) <- c("Prior GoF", "Localized Prior GoF (1%)")
datpowermaxpriorpost$nref <- factor(datpowermaxpriorpost$nref)
levels(datpowermaxpriorpost$nref) <- c("500", "1000", "2000", "3000", "4000", "5000", "50 k", "100 k")

p <- ggplot(datpowermaxpriorpost, aes(x = nref, y = power, color = score)) +
  geom_point() + geom_line(aes(group = interaction(score))) +
  geom_linerange(aes(ymin = power + sd_power, ymax = power - sd_power)) +
  facet_grid(col = vars(method), row = vars(dataset), scales = "free_x", space = "free") +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 2), title = element_blank())) +
  theme_bw() +
  xlab("Total Number of Simulations") +
  ylab("Estimated Power") +
  theme(text = element_text(size = 10),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.01, 0.3),
        legend.justification = c("left", "top"),
        legend.key.size = unit(10, 'pt'),
        # plot.margin = unit(c(0.1,0.1,-0.31,-0.5), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
# colorblindr::cvd_grid(p)
p

ggsave(filename = here("result_figures", paste0(results_name, "_power_prior_localized.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = 1.4*columnwidth,
       unit = "in")

################################################################################
# Plot power - freq rej only

datpowerfreq <- subset(datpower, method %in% c("hp.rej") & npost == 1000)
datpowermaxfreq <- subset(datpowermax, method %in% c("hp.rej") & npost == 1000)
# datpowerfreq$nref <- as.factor(datpowerfreq$nref)
# datpowermaxfreq$nref <- as.factor(datpowermaxfreq$nref)

p <- ggplot(datpowermaxfreq, aes(x = nref, y = power, color = score)) +
  geom_point() + geom_line(aes(group = interaction(score))) +
  # geom_linerange(aes(ymin = power + sd_power, ymax = power - sd_power)) +
  # facet_grid(row = vars(dataset), scales = "free") +
  facet_wrap(vars(dataset)) + #, scales = "free_y") +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 2), title = element_blank())) +
  theme_bw() +
  xlab(expression(N[ref])) +
  scale_x_continuous(breaks = c(50000, 100000), labels = c("50k", "100k")) +
  ylab("Estimated Power") +
  theme(text = element_text(size = 10),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.99, 0.99),
        legend.justification = c("right", "top"),
        legend.key.size = unit(10, 'pt'),
        plot.margin = unit(c(5.5, 9.5, 5.5, 5.5), "pt"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
# colorblindr::cvd_grid(p)
p

ggsave(filename = here("result_figures", paste0(results_name, "_power_freq_max_npost_1000.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = 0.7*columnwidth,
       unit = "in")

################################################################################
# Plot power - freq - rej loclin ridge - npost 1000

datpowerfreq <- subset(datpower, method %in% c("hp.rej", "hp.loclin", "hp.ridge") & npost == 1000)
datpowermaxfreq <- subset(datpowermax, method %in% c("hp.rej", "hp.loclin", "hp.ridge") & npost == 1000)
datpowermaxfreq$method <- factor(datpowermaxfreq$method, levels = c("hp.rej", "hp.loclin", "hp.ridge"))
levels(datpowermaxfreq$method) <- c("Rejection", "Local Linear Regression", "Ridge Regression")

p <- ggplot(datpowermaxfreq, aes(x = nref, y = power, color = score)) +
  geom_point() + geom_line(aes(group = interaction(score))) +
  # geom_linerange(aes(ymin = power + sd_power, ymax = power - sd_power)) +
  facet_grid(row = vars(dataset), col = vars(method)) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 2), title = element_blank())) +
  theme_bw() +
  xlab(expression(N[ref])) +
  scale_x_continuous(breaks = c(50000, 100000), labels = c("50k", "100k")) +
  ylab("Estimated Power") +
  theme(text = element_text(size = 10),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.99, 0.7),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(10, 'pt'),
        plot.margin = unit(c(5.5, 9.5, 5.5, 5.5), "pt"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
p

ggsave(filename = here("result_figures", paste0(results_name, "_power_freq_max_npost_1000_rej_loclin_ridge.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = columnwidth * 1.4,
       unit = "in")

################################################################################
# Plot power - rej loclin ridge - all npost

datpowerfreq <- subset(datpower, method %in% c("hp.rej", "hp.loclin", "hp.ridge"))
datpowermaxfreq <- subset(datpowermax, method %in% c("hp.rej", "hp.loclin", "hp.ridge"))
datpowermaxfreq$method <- factor(datpowermaxfreq$method, levels = c("hp.rej", "hp.loclin", "hp.ridge"))
levels(datpowermaxfreq$method) <- c("Rejection", "Local Linear Regression", "Ridge Regression")
datpowermaxfreq$nref <- factor(datpowermaxfreq$nref)


p <- ggplot(datpowermaxfreq, aes(x = npost, y = power, color = score, linetype = nref)) +
  geom_point() + geom_line(aes(group = interaction(score,nref))) +
  # geom_linerange(aes(ymin = power + sd_power, ymax = power - sd_power), show.legend = FALSE) +
  facet_grid(row = vars(dataset), col = vars(method)) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 2), title = element_blank())) +
  theme_bw() +
  xlab(expression(N[post])) +
  scale_linetype_discrete(labels = c("50k", "100k"), name = expression(N[ref])) +
  # scale_x_continuous(breaks = c(50000, 100000), labels = c("50k", "100k")) +
  ylab("Estimated Power") +
  theme(text = element_text(size = 10),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.66, 0.7),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(10, 'pt'),
        plot.margin = unit(c(5.5, 9.5, 5.5, 5.5), "pt"),
        legend.box = "horizontal",
        legend.title.position = "left",
        legend.margin = margin(2, 2, 2, 2)
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
p

ggsave(filename = here("result_figures", paste0(results_name, "_power_freq_max_all_npost_rej_loclin_ridge.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = columnwidth * 1.4,
       unit = "in")

################################################################################
# Plot power - rej - npost 1000 - K varying

datpowerfreq <- subset(datpower, method %in% c("hp.rej") & npost == 1000)
datpowermaxfreq <- subset(datpowermax, method %in% c("hp.rej") & npost == 1000)

datpowerfreq$method <- factor(datpowermaxfreq$method, levels = c("hp.rej"))
levels(datpowerfreq$method) <- c("Rejection")
datpowerfreq$score <- factor(datpowerfreq$score, levels = c("lof", "kNN"))
levels(datpowerfreq$score) <- c("LOF", "kNN")
datpowerfreq$nref <- factor(datpowerfreq$nref)
levels(datpowerfreq$nref) <- c("N[ref]==50~k", "N[ref]==100~k")

datpowermaxfreq$method <- factor(datpowermaxfreq$method, levels = c("hp.rej"))
levels(datpowermaxfreq$method) <- c("Rejection")
datpowermaxfreq$nref <- factor(datpowermaxfreq$nref)
levels(datpowermaxfreq$nref) <- c("N[ref]==50~k", "N[ref]==100~k")

p <- ggplot(datpowerfreq, aes(x = K, y = power, color = score)) +
  geom_point() + geom_line(aes(group = interaction(method, score, nref))) +
  geom_abline(data = datpowermaxfreq, aes(intercept = power, slope = 0, color = score), show.legend = FALSE) +
  facet_grid(col = vars(dataset), row = vars(nref), labeller = label_parsed) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 1), title = element_blank())) +
  theme_bw() +
  xlab(expression(k)) +
  theme(text = element_text(size = 9),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.3, 0.55),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(9, 'pt'),
        # plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
p

ggsave(filename = here("result_figures", paste0(results_name, "_power_freq_max_npost_1000_rej_K_vary.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = columnwidth * 1.4,
       unit = "in")

################################################################################
################################################################################
# Plot pvals - format
################################################################################
################################################################################

k_all <- 1:20
format_pval_tp <- function(pp) {
  pvaldata <- pp$pval
  datpvalstmp <- as.data.frame(apply(pvaldata, 2, sort))
  colnames(datpvalstmp) <- c(k_all, "max")
  datpvalstmp$xid <- 1:nrow(datpvalstmp) / nrow(datpvalstmp)
  return(datpvalstmp)
}

format_plot_pvals <- function(res) {
  dat <- lapply(res[c(1, 2)], format_pval_tp)
  dat <- mapply(function(x, y) {x$score <- y; return(x)}, dat, names(dat), SIMPLIFY = FALSE)
  dat <- do.call(rbind, dat)
  dat <- tidyr::pivot_longer(dat, cols = -c(score, xid),
                             names_to = "K",
                             values_to = "pval")
  dat$K <- factor(dat$K, levels = c(k_all, "max"))
  dat$dataset <- res$dataset
  dat$test_in_alternative <- res$test_in_alternative
  dat$method <- res$method
  dat$nref <- res$nref
  dat$npost <- res$npost
  return(dat)
}

datpval <- lapply(all_res, format_plot_pvals)
datpval <- do.call(rbind, datpval)
datpval <- subset(datpval, test_in_alternative == FALSE)
datpval$dataset <- factor(datpval$dataset, levels = c("gaussianlaplace", "depindep", "human")) # c("human", "depindep", "gaussianlaplace"))
datpval$eps <- datpval$npost / datpval$nref
datpval$nref <- factor(datpval$nref, levels = c(500, 1000, 2000, 3000, 4000, 5000, 50000, 100000))

datpval <- datpval[(datpval$score == "lof" & datpval$K == "max") | (datpval$score == "kNN" & datpval$K == "1"), ]
# datpval$method <- factor(datpval$method, levels = c("gof.freq.0.01", "gof.hp.rej.0.01", "gof.hp.loclin.0.01", "gof.hp.ridge.0.01"))

datpval$score <- factor(datpval$score, levels = c("lof", "kNN"))
levels(datpval$score) <- c("LOF", "kNN")

ks_test_stat <- function(pval_vec) {
  kk <- ks.test(x = pval_vec, y = "punif", min = 0, max = 1)
  return(c(kk$statistic, p.value = kk$p.value))
}

################################################################################
# Plot pvals - prior

datpvalprior <- subset(datpval, method == "prior")
datpvalprior$nref <- factor(datpvalprior$nref)

datpvalpriorks <- array2DF(tapply(datpvalprior$pval,
                                  list(datpvalprior$nref, datpvalprior$score, datpvalprior$dataset),
                                  ks_test_stat,
                                  simplify = FALSE))
colnames(datpvalpriorks) <- c("nref", "score", "dataset", "D", "p.value")
datpvalpriorks$D <- signif(datpvalpriorks$D, 2)
datpvalpriorks$p.value <- formatC(datpvalpriorks$p.value, format = "e", digits = 1)
datpvalpriorks$dataset <- factor(datpvalpriorks$dataset, levels = c("gaussianlaplace", "depindep", "human"))
datpvalpriorks$nref <- factor(datpvalpriorks$nref, levels = c(500, 1000, 2000, 3000, 4000, 5000))

levels(datpvalprior$dataset) <- c("Laplace - Gaussian", "Dep-Indep", "Human-like")
levels(datpvalpriorks$dataset) <- c("Laplace - Gaussian", "Dep-Indep", "Human-like")
datpvalprior <- subset(datpvalprior, !(nref %in% c(2000, 4000)))
datpvalpriorks <- subset(datpvalpriorks, !(nref %in% c(2000, 4000)))
levels(datpvalprior$nref) <- paste0("N[ref]+N[calib]==",c(500, 1000, 2000, 3000, 4000, 5000))
levels(datpvalpriorks$nref) <- paste0("N[ref]+N[calib]==",c(500, 1000, 2000, 3000, 4000, 5000))

# datpvalprior$D <- ave(datpvalprior$pval, datpvalprior$nref, datpvalprior$score, datpvalprior$dataset, FUN = ks_test)


p <- ggplot(datpvalprior, aes(x = xid, y = pval, color = score)) +
  geom_line() +
  facet_grid(row = vars(nref), col = vars(dataset), labeller = label_parsed) +
  geom_abline(intercept = 0, slope = 1) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(linewidth = 1.5), title = element_blank())) +
  # ggtitle("Prior GOF") +
  theme_bw() +
  xlab("Theoretical quantiles") +
  ylab("Empirical quantiles") +
  # geom_text(aes(x = 0.01, y = 1 - 0.15 * (score == "kNN"),
  #               hjust = "left", vjust = "top",
  #               label = p.value), data = datpvalpriorks,
  #           show.legend = FALSE) +
  coord_fixed() +
  theme(text = element_text(size = 10),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.99, 0.01),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(10, 'pt'),
        # plot.margin = unit(c(0.1,0.1,-0.31,-0.5), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
p

ggsave(filename = here("result_figures", paste0(results_name, "_pvals_H0_prior.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = twocolumnwidth * 1.2,
       unit = "in")


################################################################################
# Plot pvals - prior - ks test only

levels(datpvalpriorks$nref) <- c(500, 1000, 2000, 3000, 4000, 5000)
datpvalpriorks$p.value <- as.numeric(datpvalpriorks$p.value)
datpvalpriorks$score <- factor(datpvalpriorks$score, levels = c("LOF", "kNN"))
p <- ggplot(datpvalpriorks, aes(x = nref, y = p.value, color = score)) +
  geom_point() + geom_line(aes(group = interaction(score))) +
  geom_abline(intercept = 0.05, slope = 0, linetype = 2) +
  facet_wrap(vars(dataset)) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(size = 2), title = element_blank())) +
  theme_bw() +
  xlab(expression(N[ref]+N[calib])) +
  # scale_x_continuous(breaks = c(500, 1:5*1000)) +
  ylab("KS test p value") +
  # ggtitle("Prior GOF") +
  theme(text = element_text(size = 9),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.01, 0.99),
        legend.justification = c("left", "top"),
        legend.key.size = unit(9, 'pt'),
        # plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
p

ggsave(filename = here("result_figures", paste0(results_name, "_kstest_H0_prior.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = 0.7*columnwidth,
       unit = "in")

################################################################################
# Plot pval - freq only - 1000

ks_test_stat <- function(pval_vec) {
  kk <- ks.test(x = pval_vec, y = "punif")
  return(c(p.value = kk$p.value))
}

datpvalfreq <- subset(datpval, method %in% c("hp.rej") & npost == 1000)
datpvalfreq$method <- factor(datpvalfreq$method, levels = c("hp.rej"))
datpvalfreq$nref <- factor(datpvalfreq$nref, levels = c(50000, 1e+05))
datpvalfreq$x <- datpvalfreq$xid

datpvalfreq <- subset(datpvalfreq, method != "freq")

datpvalfreqks <- array2DF(tapply(datpvalfreq$pval,
                                 list(datpvalfreq$nref, datpvalfreq$npost, datpvalfreq$method, datpvalfreq$score, datpvalfreq$dataset),
                                 ks_test_stat,
                                 simplify = FALSE))
colnames(datpvalfreqks) <- c("nref", "npost", "method", "score", "dataset", "p.value")
datpvalfreqks <- datpvalfreqks[!sapply(datpvalfreqks$p.value, is.null),]
# datpvalfreqks$p.value <- do.call(c, datpvalfreqks$p.value)
datpvalfreqks$p.value <- formatC(datpvalfreqks$p.value, format = "e", digits = 1)
datpvalfreqks$method <- factor(datpvalfreqks$method, levels = c("hp.rej"))
datpvalfreqks$npost <- factor(datpvalfreqks$npost, levels = sort(as.numeric(unique(datpvalfreqks$npost))))
datpvalfreqks$nref <- factor(datpvalfreqks$nref, levels = sort(as.numeric(unique(datpvalfreqks$nref))))

datpvalfreq$dataset <- factor(datpvalfreq$dataset, levels = c("gaussianlaplace", "depindep", "human"))
datpvalfreqks$dataset <- factor(datpvalfreqks$dataset, levels = c("gaussianlaplace", "depindep", "human"))
levels(datpvalfreq$dataset) <- c("Laplace - Gaussian", "Dep-Indep", "Human-like")
levels(datpvalfreqks$dataset) <- c("Laplace - Gaussian", "Dep-Indep", "Human-like")


levels(datpvalfreq$nref) <- c("N[ref]==50~k", "N[ref]==100~k")
levels(datpvalfreqks$nref) <- c("N[ref]==50~k", "N[ref]==100~k")

p <- ggplot(datpvalfreq, aes(x = xid, y = pval, color = score)) +
  geom_line() +
  facet_grid(row = vars(nref), col = vars(dataset), labeller = label_parsed) +
  geom_abline(aes(intercept = 0, slope = 1)) +
  # geom_text(aes(x = 0.01, y = 1 - 0.12 * (score == "kNN"),
  #               hjust = "left", vjust = "top",
  #               label = p.value), data = datpvalfreqks, show.legend = FALSE) +
  # geom_hline(yintercept = 0.05) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(linewidth = 1.5), title = element_blank())) +
  theme_bw() +
  xlab("Theoretical quantiles") +
  ylab("Empirical quantiles") +
  # ggtitle("Post Inference GOF (2%)") +
  coord_fixed() +
  theme(text = element_text(size = 10),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.99, 0.01),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(10, 'pt'),
        # plot.margin = unit(c(0.1,0.1,-0.31,-0.5), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
p

ggsave(filename = here("result_figures", paste0(results_name, "_pval_H0_freq_1000.pdf")),
       plot = p,
       width = twocolumnwidth,
       height = columnwidth * 1.5,
       unit = "in")

################################################################################
# Plot pval - all methods - npost = 1000

ks_test_stat <- function(pval_vec) {
  kk <- ks.test(x = pval_vec, y = "punif")
  return(c(p.value = kk$p.value))
}

datpvalfreq <- subset(datpval, method %in% c("hp.rej", "hp.loclin", "hp.ridge") & npost == 1000)
datpvalfreq$method <- factor(datpvalfreq$method, levels = c("hp.rej", "hp.loclin", "hp.ridge"))
levels(datpvalfreq$method) <- c("Rejection", "Local Linear Regression", "Ridge Regression")
levels(datpvalfreq$dataset) <- c("Laplace - Gaussian", "Dep-Indep", "Human-like")
datpvalfreq$nref <- factor(datpvalfreq$nref)
datpvalfreq$x <- datpvalfreq$xid

# datpvalfreqks <- array2DF(tapply(datpvalfreq$pval,
#                                  list(datpvalfreq$nref, datpvalfreq$npost, datpvalfreq$method, datpvalfreq$score, datpvalfreq$dataset),
#                                  ks_test_stat,
#                                  simplify = FALSE))
# colnames(datpvalfreqks) <- c("nref", "npost", "method", "score", "dataset", "p.value")
# datpvalfreqks$p.value[sapply(datpvalfreqks$p.value, is.null)] <- NA
# datpvalfreqks$p.value <- formatC(datpvalfreqks$p.value, format = "e", digits = 1)
# datpvalfreqks$npost <- factor(datpvalfreqks$npost, levels = sort(as.numeric(unique(datpvalfreqks$npost))))

library(gtable)
library(grid)
library(gridExtra)

annotation_custom2 <- function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, data) {
  layer(data = data, stat = StatIdentity, position = PositionIdentity,
        geom = GeomCustomAnn, inherit.aes = FALSE, params = list(grob = grob,
                                                                 xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax))
  }

ptmp <- ggplot(datpvalfreq, aes(x = xid, y = pval, color = score, linetype = nref)) +
  geom_line() +
  facet_grid(col = vars(method), row = vars(dataset)) +
  geom_abline(aes(intercept = 0, slope = 1)) +
  # geom_hline(yintercept = 0.05) +
  scale_linetype_discrete(labels = c("50k", "100k"), name = expression(N[ref])) + guides(linetype = "none") +
  # scale_linetype_discrete(guide = element_blank(),
                          # labels = c("50k", "100k")) +
  # geom_text(aes(x = 0.01, y = 1 - 0.2 * (score == "kNN") - 0.1 * (nref == "1e+05"),
  #               hjust = "left", vjust = "top",
  #               label = p.value), data = datpvalfreqks) +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(linewidth = 1.5), title = "Score")) +
  theme_bw() +
  xlab("Theoretical quantiles") +
  ylab("Empirical quantiles") +
  # ggtitle("Post Inference GOF (2%)") +
  coord_fixed() +
  theme(text = element_text(size = 10),
        # title = element_text(size = 7),
        # panel.grid.minor = element_blank(),
        legend.position = c(0.99, 0.7),
        legend.justification = c("right", "bottom"),
        legend.key.size = unit(10, 'pt'),
        # plot.margin = unit(c(0.1,0.1,-0.31,-0.5), "cm"),
        # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)
  )
ptmp

e1 <- ggplot(datpvalfreq, aes(x = xid, y = pval, color = score, linetype = nref)) +
  geom_line() +
  facet_grid(col = vars(method), row = vars(dataset)) +
  geom_abline(aes(intercept = 0, slope = 1)) +
  # geom_hline(yintercept = 0.05) +
  scale_linetype_discrete(labels = c("50k", "100k"), name = expression(N[ref])) + guides(color = "none") +
  scale_color_viridis_d(end = 0.8, option = "B", guide = guide_legend(override.aes = list(linewidth = 1.5), title = "Score")) +
  theme_bw() +
  xlab("Theoretical quantiles") +
  ylab("Empirical quantiles") +
  # ggtitle("Post Inference GOF (2%)") +
  coord_fixed() +
  theme(text = element_text(size = 10),
        legend.key.size = unit(10, 'pt'),
  )
leg1 <- gtable_filter(ggplot_gtable(ggplot_build(e1)), "guide-box")
leg1Grob <- grobTree(leg1)

dummy_data = data.frame(dataset = "Laplace - Gaussian", method = "Local Linear Regression")
dummy_data$dataset <- factor(dummy_data$dataset, levels = c("Laplace - Gaussian", "Dep-Indep", "Human-like"))
dummy_data$method <- factor(dummy_data$method, levels = c("Rejection", "Local Linear Regression", "Ridge Regression"))

p <- ptmp +
  annotation_custom2(leg1Grob, xmin = 0.5, ymin = -0.65, data = dummy_data)
p

ggsave(filename = here("result_figures", paste0(results_name, "_pval_H0_rej_loclin_ridge.pdf")),
       plot = p,
       width = columnwidth*2,
       height = columnwidth*2,
       unit = "in")

