# Copyright (C) {2024} {GLM, PB, AE, JMM}
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# RScript to generate, from a given header file and reftable.bin file obtained using diyabc,
# the equivalent of reftableRF files, parameter files and sumstat files in a txt
# format for each scenario separately.
#
# Note: The order of the parameters in the output files has been changed to correspond
# to an order compatible with the simulation of summary statistics with the -o option in diyabc
# (see the order in which the parameters appear in the description of each scenario in the header file).
#
# REQUIREMENTS:
# - File "headerRF_for_depindep_fast_NoConditionMediumMoins.txt"
# - File "diyabc_generated_reftableRF_depindep_fast_NoConditionMediumMoins.bin"
#   Generated by script "01_Generate_reftableRF.bin_for_depindep_fast_NoConditionMediumMoins.sh".

################
# Set up
rm(list=ls())
library(here)


################
library(abcrf)
options(max.print=100000)

#### Two case studies can be processed in the present script
# human.fast.case: human like example
# depindep.case: dep indep example
human.fast.case <- FALSE
depindep.case <- TRUE

# Input and output file names
if (human.fast.case == TRUE) {
  file.reference.sim <- "diyabc_generated_reftableRF_human_fast.bin"
  file.header <- "headerRF_for_diyabc_generated_reftableRF_human_fast.txt"
  output.file.prefix <- "human_fast_reftableRF_110000"
}
if (depindep.case == TRUE) {
  file.reference.sim <- "diyabc_generated_reftableRF_depindep_fast_NoConditionMediumMoins.bin"
  file.header <- "headerRF_for_depindep_fast_NoConditionMediumMoins.txt"
  output.file.prefix <- "depindep_fast_NoConditionMediumMoinsT_reftableRF_110000"
}

# Importation of the reference table and observed data
reftable <- readRefTable(filename = file.reference.sim, header = file.header)
PARAM.S <- as.data.frame(reftable$params) # the parameter values
STAT.S <- as.data.frame(reftable$stats) # the summary statistics
index_scen <- reftable$scenarios # the model indexes
N.scen <- reftable$nscen # the number of scenarios
N.rec <- reftable$nrec # the number simulations
N.param <- ncol(reftable$param) # the number of parameters
N.stat <- ncol(reftable$stats) # the number of summary statistics

### Showing Some details about my data
cat("Details about the Data to be analyzed","\n")
cat(sprintf("Number of simulations in the reference table:"),N.rec,"\n")
cat(sprintf("Number of scenarios (i.e. models) in the reference table:"),N.scen,"\n")
cat(sprintf("Number of parameters recovered from the reference tables;"),N.param,"\n")
for (j in 1:N.scen) {
  toto = PARAM.S[index_scen==j,]
  cat("Data scenario #",j, "Nbre of parameters = ",ncol(toto[,colSums(is.na(toto)) == 0]),"\n")
}
for (j in 1:N.scen) cat("Data scenario #",j, "Nbre of particules = ",nrow(STAT.S[index_scen==j,]),"\n")
cat(sprintf("Summary statistics for the analysis:"),N.stat,"\n")
cat("\n")

############################################################################################################################################################################################
############# generating the equivalent of reftableRF files, parameter files and sumstat files in a txt format for each scenario separately ##################################################
############################################################################################################################################################################################
for (i.scen in 1:N.scen)
{
  cat("Processing Data of Scenario #",i.scen,"\n")
  cat("Nbre of simulations (particules) available:",sum(index_scen==i.scen),"\n")

  PARAM.S.scen.ready.for.diyabc=PARAM.S[index_scen==i.scen,]
  # remove columns with only NA
  PARAM.S.scen.ready.for.diyabc.sans.na <- PARAM.S.scen.ready.for.diyabc[, colSums(is.na(PARAM.S.scen.ready.for.diyabc)) == 0]

  if (human.fast.case == TRUE) {
    # For Humans SNP scenarios: reorganise the dataframe with the parameters according to the scenario order in the header file
    if (i.scen == 1) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t1", "t2", "d3", "Nbn3", "d4", "Nbn4", "N34", "t3", "d34", "Nbn34", "t4", "Na")
    } else if (i.scen == 2) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t1", "ra", "t2", "d3", "Nbn3", "d4", "Nbn4", "N34", "t3", "d34", "Nbn34", "t4", "Na")
    } else if (i.scen == 3) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t1", "ra", "t2", "d3", "Nbn3", "d4", "Nbn4", "N34", "t3", "d34", "Nbn34", "t4", "Na")
    } else if (i.scen == 4) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t11", "t22", "d3", "Nbn3", "t33", "d4", "Nbn4", "t44", "Na")
    } else if (i.scen == 5) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t11", "ra", "t22", "d3", "Nbn3", "t33", "d4", "Nbn4", "t44", "Na")
    } else if (i.scen == 6) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t11", "ra", "t22", "d3", "Nbn3", "t33", "d4", "Nbn4", "t44", "Na")
    }
  }

  if (depindep.case == TRUE) {
    # For depindep scenarios: reorganise the dataframe with the parameters according to the scenario order in the header file
    if (i.scen == 1) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t4", "t3", "t2")
    } else if (i.scen == 2) {
      ordre.param <- c("N1", "N2", "N3", "N4", "t4", "t3", "t2")
    }
  }

  PARAM.S.scen.ready.for.diyabc.sans.na.bon.ordre.param <- PARAM.S.scen.ready.for.diyabc.sans.na[ordre.param]
  # Create a df dataframe with a column called ‘scenario’.
  n = sum(index_scen==i.scen)
  df <- data.frame(scenario = rep(i.scen, n))
  PARAM.S.scen.ready.for.diyabc.sans.na.bon.ordre.param.final = cbind(df,PARAM.S.scen.ready.for.diyabc.sans.na.bon.ordre.param)

  STAT.S.scen = STAT.S[index_scen==i.scen,]
  STAT.S.scen.final=cbind(df,STAT.S.scen)

  # Generate outputfiles
  write.table(file=paste0(output.file.prefix,"_param_S",i.scen,".txt"),PARAM.S.scen.ready.for.diyabc.sans.na.bon.ordre.param.final,quote=F,col.names=T,row.names=F)
  write.table(file=paste0(output.file.prefix,"_sumstats_S",i.scen,".txt"),STAT.S.scen.final,quote=F,col.names=T,row.names=F)
  write.table(file=paste0(output.file.prefix,"_param_sumstats_S",i.scen,".txt"),cbind(PARAM.S.scen.ready.for.diyabc.sans.na.bon.ordre.param.final,STAT.S.scen),quote=F,col.names=T,row.names=F)
}

# Note: the txt file paste0(output.file.prefix,"_param_S",i.scen,".txt")
# are those that will be used using the -o option in diyabc
# to generate sumstats from a given set of parameter values


####################################################################################################################################
####################################################################################################################################
########################################################### END #####################################################################
####################################################################################################################################
####################################################################################################################################

